layout(local_size_x = 16, local_size_y = 16) in;
layout(binding = 0) uniform sampler2D uSrcTexture;
layout(binding = 1, rgba8) uniform writeonly highp image2D uDstImage;

void main() {
    ivec2 dstCoord = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dstSize = imageSize(uDstImage);
    if (dstCoord.x >= dstSize.x || dstCoord.y >= dstSize.y) {
        return;
    }

    vec2 uv = (vec2(dstCoord) + 0.5) / vec2(dstSize);
    vec4 color = texture(uSrcTexture, uv);
    imageStore(uDstImage, dstCoord, color);
}
